### ISSUE TITLE
Do you have any related papers on this project?

### ISSUE THREAD

**Issue by q110110543** [jjjj0458/Deep-Reinforcement-Learning-for-Solving-Job-Shop-Scheduling-Problems#1]
Hello,

**Comment by jjjj0458** [comment]
hi 
https://ndltd.ncl.edu.tw/cgi-bin/gs32/gsweb.cgi/login?o=dnclcdr&s=id=%22107NCTU5031006%22.&searchmode=basic

**Comment by q110110543** [comment]
你好啊，謝謝您提供的論文鏈接，但我非國立交大的學生，外校好像不能下載您的論文，能向您請求一下原文文件，或者其他公開鏈接麽

**Comment by q110110543** [comment]
您好啊,您的論文好像要限制到2023年,請問能私下參考借閲一下您的論文麽,您的成果對我很重要,希望能夠引用您的論文!!!
=========================================
书刊(篇)名: 深度强化学习求解零工式排程问题 = Deep Reinforcement Learning for Solving Job Shop Scheduling Problems
作者: 张铨晋
其他作者: 刘建良; 林春成; Chang, Chuan-Chin; Liu, Chien-Liang; Lin, Chun-Cheng
主题: 零工式排程问题; 深度学习; 强化学习; job shop scheduling problem; deep learning; reinforcement learning
附注: 纸本论文全文开放日期 2023/08/28
校内电子全文开放日期 2023/08/28
校外电子全文开放日期 不公开
国图电子全文开放日期 不公开
